- name: string comparation
  hosts: local
  connection: local
  tasks:
    - name: reading files from files
      ansible.builtin.include_vars:
        file: message.yml
        name: MESSAGE
    - name : printing files
      ansible.builtin.debug:
        msg: "env {{ MESSAGE.env }} name space: {{ MESSAGE.name_space }}"
