- name: reading variable from files
  hosts: local
  connection: local
  vars_files:
    - message.yml
  tasks:
    - name: "reading from file"
      ansible.builtin.debug:
        msg: "hello vinod {{ message }}"
