- name: task level variable
  hosts: local
  connection: local
  tasks:
    - name: print the  variable1
      vars:
        COURSE: "Asible"
        DURATION: 120hours
        TRAINER: siva kumar
      ansible.builtin.debug:
        msg: "Course {{COURSE}} and duration {{DURATION}} and trainer is {{TRAINER}}"

    