- name: reading variable from files
  hosts: local
  connection: local
  vars_files:
    - course.yml
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "Course {{ COURSE }}, Duration {{ DURATION }} and Trainer is {{ TRAINER_NAME }}"
