- name: reading variable from prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: please enter the course name
      private: false # show the value to user if any sensitive information read make it as false
    - name: DURATION
      prompt: please enter the duration
      private: false
    - name: TRAINER
      prompt: enter the trainer name
      private: false
  tasks:
    - name: print the variables
      vars_prompt:
        - name: USERNAME
          prompt: ener the username
          private: false
        - name: PASSWORD
          prompt: enter the password
          private: true
      ansible.builtin.debug:
        msg: "Course {{ COURSE}}, Duration {{ DURATION }} and Trainer {{ TRAINER }}"

