- name: install packages
  hosts: local
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - git
        - maven
        - java
        - nginx
        - mysql
        - zip


